pull_request_rules:
  - name: merge scala-steward PRs
    conditions:
      - "author=fgrutsch"
      - "head~=^update\/.+$"
      - "status-success=Build and Test (ubuntu-latest, 3.1.0, 8)"
      - "status-success=Build and Test (ubuntu-latest, 3.1.0, 11)"
      - "status-success=Build and Test (ubuntu-latest, 3.1.0, 17)"
    actions:
      merge:
        method: squash